# Generated by Django 5.1.4 on 2024-12-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, help_text='Enter a unique username', max_length=30, null=True, unique=True)),
                ('email', models.CharField(db_index=True, max_length=255, unique=True)),
                ('bio', models.CharField(blank=True, help_text='Enter a unique username', max_length=50, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('Qualification', models.CharField(choices=[(1, 'B.Tech'), (1, 'M.Tech'), (1, 'B.B.A'), (1, 'M.B.A')], db_index=True, max_length=100, null=True)),
            ],
        ),
    ]
